# Generated by Django 4.1.5 on 2023-01-13 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craft',
            name='price',
        ),
        migrations.RemoveField(
            model_name='craftsman',
            name='loction',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='loction',
        ),
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='craftsman',
            name='location',
            field=models.CharField(default='Jordan', max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='location',
            field=models.CharField(default='Jordan', max_length=255),
        ),
        migrations.AlterField(
            model_name='craft',
            name='craftsman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='craftsman', to='accounts.craftsman'),
        ),
    ]
