# Generated by Django 4.1.5 on 2023-01-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_craft_price_remove_craftsman_loction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftsman',
            name='phone',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
