# Generated by Django 4.1.5 on 2023-01-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_craftsman_id_remove_customer_id_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftsman',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
