# Generated by Django 4.1.5 on 2023-01-14 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_craftsman_phone_alter_customer_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('reviewText', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='craft',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='craftsman',
            name='email',
        ),
        migrations.RemoveField(
            model_name='craftsman',
            name='name',
        ),
        migrations.RemoveField(
            model_name='craftsman',
            name='phone',
        ),
        migrations.AddField(
            model_name='booking',
            name='craftsman',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.craftsman'),
        ),
        migrations.AddField(
            model_name='booking',
            name='serviceType',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='craftsman',
            name='craft',
            field=models.CharField(choices=[('HomeRepairs', 'Home repairs'), ('Plumbing', 'Plumbing Work'), ('Electrical', 'electrical work'), ('Packing', 'Moving and packing'), ('HVAC', 'HVAC repair'), ('Carpentry', 'Carpentry'), ('Painting', 'Painting')], default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='craftsman',
            name='rating',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'customer'), ('Craftsman', 'Craftsman')], default='customer', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Craft',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='review',
            name='craftsman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.craftsman'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
