# Generated by Django 4.1.5 on 2023-01-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_craftsmanprofile_custmerprofile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='craftsmanprofile',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='craftsmanprofile',
            name='location',
        ),
        migrations.AddField(
            model_name='craftsmanprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
