# Generated by Django 4.1.5 on 2023-01-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_name_craftsmanprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custmerprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
