# Generated by Django 4.1.5 on 2023-01-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_custmerprofile_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custmerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
