# Generated by Django 4.1.5 on 2023-01-16 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_custmerprofile_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craftsmanprofile',
            name='craft',
        ),
    ]
