# Generated by Django 4.1.5 on 2023-01-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_craftsmanprofile_craft'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftsmanprofile',
            name='craft',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
