# Generated by Django 4.1.5 on 2023-01-17 11:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_craftsmanprofile_craft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='craftsmanprofile',
            name='craft',
        ),
        migrations.RemoveField(
            model_name='craftsmanprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='custmerprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='craftsmanprofile',
            name='crafts',
            field=models.CharField(blank=True, choices=[('PLUMBING_WORK', 'plumbing Work'), ('ELECTRICAL_WORK', 'Electrical Work'), ('MOVING_AND_PACKING', 'Moving and packing'), ('HOME_REPAIRS', 'Home_Repairs'), ('POWER_WASHING', 'Power Washing'), ('PAINTING', 'Painting'), ('CARPENTRY', 'Carpentry'), ('HVAC_REPAIR', 'HVAC_repair')], default='Electrical_Work', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='craftsmanprofile',
            name='location',
            field=models.CharField(blank=True, choices=[('AMMAN', 'Amman'), ('ZARQA', 'Zarqa'), ('BALQA', 'Balqa'), ('MADABA', 'Madaba'), ('KARAK', 'Karak'), ('IRBID', 'Irbid'), ('MAFRAQ', 'Mafraq'), ('JERASH', 'Jerash'), ('TAFILAH', 'Tafilah'), ('MAAN', "Ma'an"), ('AJLOUN', 'Ajloun'), ('AQAPA', 'Aqaba')], default='Amman', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='craftsmanprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='custmerprofile',
            name='location',
            field=models.CharField(blank=True, choices=[('AMMAN', 'Amman'), ('ZARQA', 'Zarqa'), ('BALQA', 'Balqa'), ('MADABA', 'Madaba'), ('KARAK', 'Karak'), ('IRBID', 'Irbid'), ('MAFRAQ', 'Mafraq'), ('JERASH', 'Jerash'), ('TAFILAH', 'Tafilah'), ('MAAN', "Ma'an"), ('AJLOUN', 'Ajloun'), ('AQAPA', 'Aqaba')], default='Amman', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='custmerprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, region=None),
        ),
    ]
