# Generated by Django 4.1.5 on 2023-01-17 11:57

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_craftsmanprofile_craft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, choices=[('AMMAN', 'Amman'), ('ZARQA', 'Zarqa'), ('BALQA', 'Balqa'), ('MADABA', 'Madaba'), ('KARAK', 'Karak'), ('IRBID', 'Irbid'), ('MAFRAQ', 'Mafraq'), ('JERASH', 'Jerash'), ('TAFILAH', 'Tafilah'), ('MAAN', "Ma'an"), ('AJLOUN', 'Ajloun'), ('AQAPA', 'Aqaba')], default='Amman', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Contact phone number', max_length=128, region=None),
        ),
    ]
