# Generated by Django 4.1.5 on 2023-01-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_location_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftsmanprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=11),
        ),
        migrations.AlterField(
            model_name='custmerprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=11),
        ),
    ]
