# Generated by Django 4.1.5 on 2023-01-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_craftsmanprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='crafts',
            field=models.CharField(blank=True, choices=[('PLUMBING_WORK', 'plumbing Work'), ('ELECTRICAL_WORK', 'Electrical Work'), ('MOVING_AND_PACKING', 'Moving and packing'), ('HOME_REPAIRS', 'Home_Repairs'), ('POWER_WASHING', 'Power Washing'), ('PAINTING', 'Painting'), ('CARPENTRY', 'Carpentry'), ('HVAC_REPAIR', 'HVAC_repair')], default='------', max_length=50, null=True),
        ),
    ]
