# Generated by Django 4.1.5 on 2023-01-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_crafts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='craftsmanprofile',
            name='crafts',
            field=models.CharField(blank=True, choices=[('PLUMBING_WORK', 'plumbing Work'), ('ELECTRICAL_WORK', 'Electrical Work'), ('MOVING_AND_PACKING', 'Moving and packing'), ('HOME_REPAIRS', 'Home_Repairs'), ('POWER_WASHING', 'Power Washing'), ('PAINTING', 'Painting'), ('CARPENTRY', 'Carpentry'), ('HVAC_REPAIR', 'HVAC_repair')], default='Electrical Work', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='crafts',
            field=models.CharField(blank=True, choices=[('PLUMBING_WORK', 'plumbing Work'), ('ELECTRICAL_WORK', 'Electrical Work'), ('MOVING_AND_PACKING', 'Moving and packing'), ('HOME_REPAIRS', 'Home_Repairs'), ('POWER_WASHING', 'Power Washing'), ('PAINTING', 'Painting'), ('CARPENTRY', 'Carpentry'), ('HVAC_REPAIR', 'HVAC_repair')], default='Electrical Work', max_length=50, null=True),
        ),
    ]
