# Generated by Django 4.1.5 on 2023-01-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_craftsmanprofile_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftsmanprofile',
            name='average_review',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='craftsmanprofile',
            name='count_review',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
