# Generated by Django 4.1.5 on 2023-01-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_created_at_booking_day_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='description',
            field=models.TextField(blank=True, default='No description', null=True),
        ),
    ]
